# 配置复用
.pnpm-config:
    before_script:
        - corepack enable
        # corepack prepare pnpm@latest-9 --activate
        - corepack prepare --activate
        - pnpm config set store-dir .pnpm-store
    # 私有仓库配置
    # - pnpm config set @scope:registry https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    # - pnpm config set -- //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken ${CI_JOB_TOKEN}

# 公用的构建镜像配置
.docker-build-stage:
    tags:
        - docker
    stage: image
    image: docker:27.3-dind
    services:
        - docker:27.3-dind
    retry:
        max: 2
        when:
            - runner_system_failure
            - unknown_failure
            - script_failure
    script:
        # tag标记1：产物类型
        - |
            if [ "$CI_COMMIT_BRANCH" == "main" ]; then
            export IMAGE_NAME=production
            else
            export IMAGE_NAME=staging
            fi
        - version=$(cat version.txt)
        - echo $version
        # 构建镜像
        - docker build -t $USER_DOCKER_NS/$CI_PROJECT_NAME-$SUB_PACKAGE-$IMAGE_NAME:$version-$CI_COMMIT_SHORT_SHA .
        # docker login
        # - docker login -u $USER_DOCKER_REGISTRY_USER -p $USER_DOCKER_REGISTRY_PASSWORD $USER_DOCKER_REGISTRY
        # 镜像推送
        # - docker push $USER_DOCKER_NS/$CI_PROJECT_NAME-$SUB_PACKAGE-$IMAGE_NAME:$version-$CI_COMMIT_SHORT_SHA
        - image_name=$USER_DOCKER_NS/$CI_PROJECT_NAME-$SUB_PACKAGE-$IMAGE_NAME:$version-$CI_COMMIT_SHORT_SHA
        - echo "$image_name" > image.txt
    artifacts:
        paths:
            - image.txt
