variables:
  PNPM_HOME: '$CI_PROJECT_DIR/.pnpm'
  PNPM_STORE_DIR: '$CI_PROJECT_DIR/.pnpm-store'
  NODE_IMAGE: 'mapleimage123/node:20-alpine3.19'
  COREPACK_NPM_REGISTRY: 'https://registry.npmmirror.com'
  TZ: 'Asia/Shanghai'

default:
  image:
    name: $NODE_IMAGE

# workflow:
# 覆盖默认的工作流名称：默认的是当前的最新提交信息
# name: 'workflow name'

stages:
  - install
  - eslint
  - build
  - image
  - deploy
#   - notify
# 公共的步骤，可以在其他.gitlab-ci.yml文件中引用
# 如果pnpm-lock.yaml没有变化就不会执行

install-job:
  extends: .install-job

# 配置复用
.pnpm-config:
  before_script:
    - corepack enable
    - corepack prepare --activate
    - pnpm config set store-dir $PNPM_STORE_DIR
  # 私有仓库配置
  # - pnpm config set @scope:registry https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
  # - pnpm config set -- //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken ${CI_JOB_TOKEN}

# 安装依赖-workspace级别
.install-job:
  extends:
    - .pnpm-config
    - .retry
  stage: install
  tags:
    - nodejs
  script:
    - export
    - time pnpm install --frozen-lockfile
  rules:
    - changes:
        - package.json
        - pnpm-lock.yaml
    - when: never
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - $PNPM_STORE_DIR
    policy: pull-push

# 构建dist-workspace下的各个子项目共享
.build-job:
  extends:
    - .retry
  before_script:
    - pnpm config set store-dir $PNPM_STORE_DIR
  stage: build
  tags:
    - nodejs
  script:
    - echo "building $SUB_PACKAGE"
    - cd "packages/$SUB_PACKAGE"
    - time pnpm install --frozen-lockfile
    - time pnpm run build
    - APP_VERSION=$(node -p -e "require('./package.json').version")
    - echo "APP_VERSION=$APP_VERSION" >> version.env
  artifacts:
    paths:
      - 'packages/$SUB_PACKAGE/dist'
    reports:
      dotenv:
        - 'packages/$SUB_PACKAGE/version.env'
    expire_in: 1 hr
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - $PNPM_STORE_DIR
    policy: pull
  needs:
    - job: install-job
      optional: true

# 构建docker image-workspace下的各个子项目共享
.build-image-job:
  extends:
    - .retry
    - .merge-request
  stage: image
  tags:
    - docker
  image: docker:27.3-dind
  services:
    - docker:27.3-dind
  script:
    # tag标记1：产物类型
    - |
      if [ "$CI_COMMIT_BRANCH" == "main" ]; then
      export IMAGE_NAME=production
      else
      export IMAGE_NAME=staging
      fi
    - if [ -d "dist" ]; then echo "dist directory exists"; else echo "dist directory does not exist"; fi
    - echo $APP_VERSION
    # 构建镜像
    - docker build -t $USER_DOCKER_NS/$CI_PROJECT_NAME-$SUB_PACKAGE-$IMAGE_NAME:$APP_VERSION-$CI_COMMIT_SHORT_SHA -f ./packages/$SUB_PACKAGE/Dockerfile ./packages/$SUB_PACKAGE
    # docker login
    # - docker login -u $USER_DOCKER_REGISTRY_USER -p $USER_DOCKER_REGISTRY_PASSWORD $USER_DOCKER_REGISTRY
    # 镜像推送
    # - docker push $USER_DOCKER_NS/$CI_PROJECT_NAME-$SUB_PACKAGE-$IMAGE_NAME:$APP_VERSION-$CI_COMMIT_SHORT_SHA
    - image_name=$USER_DOCKER_NS/$CI_PROJECT_NAME-$SUB_PACKAGE-$IMAGE_NAME:$APP_VERSION-$CI_COMMIT_SHORT_SHA
    - echo "BUILD_IMAGE=$image_name" >> image.env
  artifacts:
    reports:
      dotenv:
        - 'image.env'
    expire_in: 2 hr

.deploy-job:
  extends:
    - .retry
    - .merge-request
  stage: deploy
  tags:
    - docker
  image: docker:27.3-dind
  script:
    - echo $BUILD_IMAGE
    - docker stop $CI_PROJECT_NAME-$SUB_PACKAGE || true
    - docker rm $CI_PROJECT_NAME-$SUB_PACKAGE || true
    - docker run --restart=always --name $CI_PROJECT_NAME-$SUB_PACKAGE --network maple-network -d -p $SUB_PACKAGE_PORT:80 $BUILD_IMAGE

.notify-success:
  extends:
    - .retry
    - .merge-request
  stage: notify
  script:
    - apk add --no-cache curl
    - >
      curl -X POST -H "Content-Type: application/json"
      -d '
      {
          "msg_type":"text",
          "content": {
              "text":"Web APP - '$SUB_PACKAGE' 部署成功"
          }
      }' https://open.feishu.cn/open-apis/bot/v2/hook/f44c17ad-06b0-4957-a5be-2b066fcef6ce

.eslint:
  extends:
    - .retry
  before_script:
    - pnpm config set store-dir $PNPM_STORE_DIR
  stage: eslint
  tags:
    - nodejs
  script:
    - cd "packages/$SUB_PACKAGE"
    - time pnpm install --frozen-lockfile
    - pnpm run lint
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - $PNPM_STORE_DIR
    policy: pull
  allow_failure: true
  needs:
    - job: install-job
      optional: true

.retry:
  retry:
    max: 2
    when:
      - runner_system_failure # 如果 runner 系统出现故障（例如，作业设置失败）
      - unknown_failure # 包含 TLS 等网络错误
      - script_failure

# NOTE 仅被合并后执行
.merge-request:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never

# 合并前执行
# TODO
# NOTE 文件改变时执行
.file-change:
  rules:
    - changes:
        - packages/$SUB_PACKAGE/**/*
