# 配置复用
.pnpm-config:
  before_script:
    - corepack enable
    - corepack prepare --activate
    - pnpm config set store-dir $PNPM_STORE_DIR
  # 私有仓库配置
  # - pnpm config set @scope:registry https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
  # - pnpm config set -- //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken ${CI_JOB_TOKEN}

# 安装依赖-workspace级别
.install-job:
  extends: .pnpm-config
  stage: install
  tags:
    - nodejs
  image: $NODE_IMAGE
  script:
    - export
    - time pnpm install --frozen-lockfile
  rules:
    - changes:
        - pnpm-lock.yaml
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - $PNPM_STORE_DIR
    policy: pull-push

# 构建dist-workspace下的各个子项目共享
.build-job:
  before_script:
    - pnpm config set store-dir $PNPM_STORE_DIR
  stage: build
  tags:
    - nodejs
  image: $NODE_IMAGE
  script:
    - echo "building $SUB_PACKAGE"
    - cd "packages/$SUB_PACKAGE"
    - time pnpm install --frozen-lockfile
    - time pnpm run build
    - APP_VERSION=$(node -p -e "require('./package.json').version")
    - echo "$APP_VERSION" > ./version.txt
  artifacts:
    paths:
      - 'packages/$SUB_PACKAGE/dist'
      - 'packages/$SUB_PACKAGE/version.txt'
    expire_in: 1 hr
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - $PNPM_STORE_DIR
    policy: pull

# 构建docker image-workspace下的各个子项目共享
.build-image-job:
  stage: image
  tags:
    - docker
  image: docker:27.3-dind
  services:
    - docker:27.3-dind
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - script_failure
  script:
    # tag标记1：产物类型
    - |
      if [ "$CI_COMMIT_BRANCH" == "main" ]; then
      export IMAGE_NAME=production
      else
      export IMAGE_NAME=staging
      fi
    - if [ -d "dist" ]; then echo "dist directory exists"; else echo "dist directory does not exist"; fi
    - version=$(cat "packages/$SUB_PACKAGE/version.txt")
    - echo $version
    # 构建镜像
    - docker build -t $USER_DOCKER_NS/$CI_PROJECT_NAME-$SUB_PACKAGE-$IMAGE_NAME:$version-$CI_COMMIT_SHORT_SHA -f ./packages/$SUB_PACKAGE/Dockerfile ./packages/$SUB_PACKAGE
    # docker login
    # - docker login -u $USER_DOCKER_REGISTRY_USER -p $USER_DOCKER_REGISTRY_PASSWORD $USER_DOCKER_REGISTRY
    # 镜像推送
    # - docker push $USER_DOCKER_NS/$CI_PROJECT_NAME-$SUB_PACKAGE-$IMAGE_NAME:$version-$CI_COMMIT_SHORT_SHA
    - image_name=$USER_DOCKER_NS/$CI_PROJECT_NAME-$SUB_PACKAGE-$IMAGE_NAME:$version-$CI_COMMIT_SHORT_SHA
    - echo "$image_name" > image.txt
  artifacts:
    paths:
      - image.txt
    expire_in: 1 hr

.deploy-job:
  stage: deploy
  tags:
    - docker
  image: docker:27.3-dind
  script:
    - image=$(cat image.txt)
    - echo $image
    - docker stop $CI_PROJECT_NAME-$SUB_PACKAGE || true
    - docker rm $CI_PROJECT_NAME-$SUB_PACKAGE || true
    - docker run --restart=always --name $CI_PROJECT_NAME-$SUB_PACKAGE --network maple-network -d -p $SUB_PACKAGE_PORT:80 $image

.notify-success:
  stage: notify
  script:
    - >
      curl -X POST -H "Content-Type: application/json"
      -d '
      {
          "msg_type":"text",
          "content": {
              "text":"Web APP - '$SUB_PACKAGE' 部署成功"
          }
      }' https://open.feishu.cn/open-apis/bot/v2/hook/f44c17ad-06b0-4957-a5be-2b066fcef6ce
  rules:
    - if: $CI_JOB_STATUS  == "success"

.notify-failure:
  stage: notify
  rules:
    - if: $CI_JOB_STATUS  == "failed"

  script:
    - >
      curl -X POST -H "Content-Type: application/json"
      -d '
      {
          "msg_type":"text",
          "content": {
              "text":"Web APP - '$SUB_PACKAGE' 部署失败"
          }
      }' https://open.feishu.cn/open-apis/bot/v2/hook/f44c17ad-06b0-4957-a5be-2b066fcef6ce
