include:
  - local: '.gitlab-ci-common.yml'

build-job-main:
  extends:
    - .build-job
    - .merge-request
  variables:
    SUB_PACKAGE: 'main'

build-image-job-main:
  extends:
    - .build-image-job
    - .merge-request
  variables:
    SUB_PACKAGE: 'main'
  dependencies:
    - build-job-main
  needs:
    - job: build-job-main

deploy-job-main:
  extends:
    - .deploy-job
    - .merge-request
  variables:
    SUB_PACKAGE: 'main'
    SUB_PACKAGE_PORT: '6040'
  needs:
    - job: build-image-job-main

# 部署成功的通知
notify-success-main:
  extends:
    - .notify-success
    - .merge-request
  variables:
    SUB_PACKAGE: 'main'
  needs:
    - job: deploy-job-main

# 部署失败的通知
# notify-failure-main:
#   extends:
#     - .notify-failure
#     - .merge-request
#   variables:
#     SUB_PACKAGE: 'main'
#   needs:
#     - job: deploy-job-main

# eslint
eslint-job-main:
  extends:
    - .eslint
  variables:
    SUB_PACKAGE: 'main'
