include:
  - local: '.gitlab-ci-common.yml'

build-job-react18-webpack:
  extends:
    - .build-job
    # - .deploy-rule
  variables:
    SUB_PACKAGE: 'react18-webpack'

build-image-job-react18-webpack:
  extends:
    - .build-image-job
  variables:
    SUB_PACKAGE: 'react18-webpack'
  dependencies:
    - build-job-react18-webpack
  needs:
    - job: build-job-react18-webpack

deploy-job-react18-webpack:
  extends:
    - .deploy-job
  variables:
    SUB_PACKAGE: 'react18-webpack'
    SUB_PACKAGE_PORT: '6043'
  needs:
    - job: build-image-job-react18-webpack

# eslint
eslint-job-react18-webpack:
  extends:
    - .eslint
    - .file-change-rule
  variables:
    SUB_PACKAGE: 'react18-webpack'
