include:
  - local: '.gitlab-ci-common.yml'

build-job-react18-webpack:
  extends: .build-job
  variables:
    SUB_PACKAGE: 'react18-webpack'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $CI_COMMIT_BRANCH == "main" 
      when: always

build-image-job-react18-webpack:
  extends: .build-image-job
  variables:
    SUB_PACKAGE: 'react18-webpack'
  dependencies:
    - build-job-react18-webpack
  needs:
    - job: build-job-react18-webpack

deploy-job-react18-webpack:
  extends: .deploy-job
  variables:
    SUB_PACKAGE: 'react18-webpack'
    SUB_PACKAGE_PORT: '6043'
  needs:
    - job: build-image-job-react18-webpack

# 部署成功的通知
notify-success-react18-webpack:
  extends: .notify-success
  variables:
    SUB_PACKAGE: 'react18-webpack'
  needs:
    - job: deploy-job-react18-webpack

# 部署失败的通知
notify-failure-react18-webpack:
  extends: .notify-failure
  variables:
    SUB_PACKAGE: 'react18-webpack'
  needs:
    - job: deploy-job-react18-webpack

lint-job-react18-webpack:
  stage: eslint
  tags:
    - nodejs
  script:
    - echo "lint-job-react18-webpack"
    - cd "packages/react18-webpack"
    - pnpm run lint