include:
  - local: ".gitlab-ci-common.yml"

build-job-vue3:
  extends: .build-job
  rules:
    - changes:
        - packages/vue3/**/*
  variables:
    SUB_PACKAGE: "vue3"  

build-image-job-vue3:
  extends: .build-image-job
  dependencies:
    - build-job-vue3
  needs:
    - job: build-job-vue3
      optional: false
  rules:
    - changes:
        - packages/vue3/**/*
  variables:
    SUB_PACKAGE: "vue3"  

deploy-job-vue3:
  extends: .deploy-job
  needs:
    - job: build-image-job-vue3
      optional: false
  rules:
    - changes:
        - packages/vue3/**/*
  variables:
    SUB_PACKAGE: "vue3"  
    SUB_PACKAGE_PORT: "6042"

# 部署成功的通知
notify-success-vue3:
  extends: .notify-success
  variables:
    SUB_PACKAGE: "vue3"   
  needs:
    - job: deploy-job-vue3
      optional: false
      
# 部署失败的通知
notify-failure-vue3:
  extends: .notify-failure
  variables:
    SUB_PACKAGE: "vue3"   
  needs:
    - job: deploy-job-vue3
      optional: false    