include:
  - local: '.gitlab-ci-common.yml'

build-job-vue3:
  extends:
    - .build-job
    - .merge-request
  variables:
    SUB_PACKAGE: 'vue3'

build-image-job-vue3:
  extends:
    - .build-image-job
    - .merge-request
  dependencies:
    - build-job-vue3
  needs:
    - job: build-job-vue3
  variables:
    SUB_PACKAGE: 'vue3'

deploy-job-vue3:
  extends:
    - .deploy-job
    - .merge-request
  needs:
    - job: build-image-job-vue3
  variables:
    SUB_PACKAGE: 'vue3'
    SUB_PACKAGE_PORT: '6042'

# 部署成功的通知
notify-success-vue3:
  extends:
    - .notify-success
    - .merge-request
  variables:
    SUB_PACKAGE: 'vue3'
  needs:
    - job: deploy-job-vue3

# 部署失败的通知
# notify-failure-vue3:
#   extends:
#     - .notify-failure
#     - .merge-request
#   variables:
#     SUB_PACKAGE: 'vue3'
#   needs:
#     - job: deploy-job-vue3

# eslint
eslint-job-vue3:
  extends:
    - .eslint
  variables:
    SUB_PACKAGE: 'vue3'
